# Generated by Django 5.0.1 on 2025-01-14 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('daily', '日报'), ('weekly', '周报'), ('monthly', '月报'), ('yearly', '年报'), ('custom', '自定义')], max_length=20, verbose_name='报告类型')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='总收入')),
                ('total_expense', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='总支出')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='bills.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '统计报告',
                'verbose_name_plural': '统计报告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='占比')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.category')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='stats.report')),
            ],
            options={
                'verbose_name': '报告明细',
                'verbose_name_plural': '报告明细',
            },
        ),
    ]
