# Generated by Django 5.0.1 on 2025-01-14 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-date'], 'verbose_name': '账单', 'verbose_name_plural': '账单'},
        ),
        migrations.AlterField(
            model_name='bill',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='bills.account', verbose_name='所属账本'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bills.category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(verbose_name='日期时间'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='description',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='type',
            field=models.CharField(choices=[('income', '收入'), ('expense', '支出')], max_length=10, verbose_name='类型'),
        ),
    ]
